name: Test Bash Scripts

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest

    steps:
     
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: '.'
	      severity: error

      - name: Basic Syntax Check
        run: |
          find . -name "*.sh" -type f | while read -r script; do
            echo "Checking syntax for: $script"
            bash -n "$script" || exit 1
          done
          echo "All scripts passed syntax check! "
